# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d13aff5a3900c5f106bf4959a03a6c2221c79a4ddb425c8fca960ee3c3c41d286e96ae378a40b8062425c3d54dcb703af83e002d2122f0922922e910397a70

test:
  secret_key_base: f6dfc726cbdcdf50f4fa9212d85d05c02ddf0c80e52864d981bc75e8a487fcb49c191d7c48a0e905f9a10ccdc6b17ff48c1f9b365a9b2e01c04a394935181646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
